spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: EDDI-TCG-Home-Spring

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    dialect: ${SPRING_DATASOURCE_DIALECT}

  jpa:
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    open-in-view: true
    database: ${SPRING_JPA_DATABASE}
    show-sql: true
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  sql:
    init:
      mode: always
      platform: ${DATABASE_PLATFORM}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

server:
  port: ${SERVER_PORT}

cors:
  allow:
    origins: ${CORS_ALLOWED_ORIGINS}

kakao:
  login-url: ${KAKAO_LOGIN_URL}
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-request-uri: ${KAKAO_TOKEN_REQUEST_URI}
  user-info-request-uri: ${KAKAO_USER_INFO_REQUEST_URI}
